version: '3'

services:
  app:
    build: .
    restart: always
    hostname: "playground.yude.jp"
    volumes:
      - /mnt/data3/share:/root/share
    networks:
      - no-inet

  cloudflared:
    image: cloudflare/cloudflared:2021.8.3
    user: root
    command: tunnel --hostname playground.yude.jp --url ssh://app:22 --loglevel info
    volumes:
      - '$HOME/.cloudflared:/root/.cloudflared'
    restart: always
    networks:
      - no-inet
      - inet

networks:
  no-inet:
    driver: bridge
    internal: true
  inet:
    driver: bridge